version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - '5672:5672'
      - '15672:15672'
      - '5673:5673'

  producer:
    image: producer
#    restart: on-failure

  producer_consumer:
    image: producer_consumer
#    restart: on-failure

  consumer:
    image: consumer
#    restart: on-failure

